version: '3.9'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - "8081:80"
    volumes:
      - ~/.satmedinfra/nextcloud:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=next
      - MYSQL_PASSWORD=Nex53124!
      - NEXTCLOUD_ADMIN_USER=nextadmin
      - NEXTCLOUD_ADMIN_PASSWORD=Adm53124!
    networks:
      - nextcloud-net
    restart: always

  db:
    image: mariadb:latest
    container_name: nextcloud_db
    volumes:
      - ~/.satmedinfra/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Roo53124!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=next
      - MYSQL_PASSWORD=Nex53124!
    networks:
      - nextcloud-net
    restart: always

volumes:
  nextcloud:
  db:

networks:
  nextcloud-net:
